### ISSUE TITLE
[HW19] Docker (знакомство)

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos21-onl/igor-vanin#21]
**Дедлайн: 30/04/2024**<br /><br />1. Установить Docker на хостовую ОС. В случае с Windows использовать WSL backend.<br />2. Убедиться, что Docker работает исправно путем запуска контейнера [hello-world](https://hub.docker.com/_/hello-world).<br />3. Установить Nginx используя [Docker образ](https://hub.docker.com/_/nginx)<br />4. Изучить следующие команды и их флаги:<br />    - `docker run` (`-i`, `-t`, `-d`, `--rm`)<br />    - `docker ps` (`-a`, `-l`, `-q`)<br />    - `docker images`<br />    - `docker start`/`docker stop`/`docker restart`<br />    - `docker exec`<br />5. Установить Nexus используя [Docker образ](https://hub.docker.com/r/sonatype/nexus3)<br />6. Установить Jenkins используя [Docker образ](https://hub.docker.com/_/jenkins)

**Comment by Rvlt135** [comment]
@AlexPykavy  выполнил задание в ветке homework-19

**Comment by AlexPykavy** [comment]
А у тебя получилось запустить сами Nexus & Jenkins как Docker контейнеры? А то вижу только, что ты образы скачал.

**Comment by Rvlt135** [comment]
99% что запускал да, надо будет перепроверить.

**Comment by AlexPykavy** [comment]
Ну тогда, закрываем issue. Можешь мержиться 😊
