### ISSUE TITLE
[HW20] Docker (volumes и network)

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos21-onl/igor-vanin#22]
**Дедлайн: 02/05/2024**<br /><br />1. Установить [Nginx](https://hub.docker.com/_/nginx) и смонтировать в него:<br />    - конфигурационный файл с хоста, который выполняет настройку HTTPS для страницы по умолчанию<br />    - директорию с сертификатами<br />2. Запустить 2 Docker контейнера (например, [Docker Getting Started](https://hub.docker.com/r/docker/getting-started) и [netshoot](https://hub.docker.com/r/nicolaka/netshoot)) с настройками сети по умолчанию и проверить есть ли между ними соединение.<br />3. Создать именованный Docker volume, который будет использоваться для хранения данных MariaDB. Установить [MariaDB](https://hub.docker.com/_/mariadb) **версии 11.0** используя ранее созданный volume. Затем:<br />    - Запустить интерактивную сессию Bash в запущенном контейнере при помощи `docker exec`<br />    - Проверить версию MariaDB через SQL запрос.<br />    - Создать БД, таблицу и запись.<br />    - Выполнить апгрейд MariaDB путем подмены версии используемого Docker образа на **11.1.2**.<br />    - Проверить, что версия MariaDB поменялась.<br />    - Проверить, что данные остались.

**Comment by Rvlt135** [comment]
@AlexPykavy  Выполнил домашку в ветке homework-20, описал в HW20.md
Единственное в задании указано обновить на на 11.1.2
Я обновил на 11.2, так как брал из официальных репозиториев версии.
Там указано:
[11.2.3-jammy, 11.2-jammy, 11.2.3, 11.2]
[11.1.4-jammy, 11.1-jammy, 11.1.4, 11.1] 
Впринципе алгоритм обновления для 11.1.2 будет такой же как и для любых других версий.

**Comment by AlexPykavy** [comment]
Принимается! Можешь мержить в `main`.
