### ISSUE TITLE
[HW3] Проверка состояния ресурсов системы

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos21-onl/igor-vanin#3]
**Дедлайн: 16/02/2024**<br /><br />1. Познакомиться с утилитой `Midnight Commander`, установить её на VM и узнать с помощью неё все папки верхнего уровня файловой системы.<br />2. Установить `PowerShell` на VM и проверить, что он работаёт путем выполнения каких-нибудь простейших команд.<br />3. Создать простейший bash-скрипт `sysinfo.sh`, который собирает данные о:<br />	- количестве свободной оперативной памяти<br />	- текущей загрузке процессора<br />	- текущем IP адресе(ах)<br />и выводит их в формате `ключ: значение`, причем все ключи заменить на русские названия. Например, чтобы вместо «Mem: 1024Mb» выводилось «Память: 1024Мб». Для написания скрипта рекомендуется использовать утилиты `awk`, `grep` и `sed`.<br />4. (\*\*) Cоздать файл `immortalfile`, запретить его удаление даже пользователем `root` и попытаться его удалить из под `root`, результатом должно быть “Operation not permitted”. Подсказка: `chattr`.<br />5. (\*\*\*) Выполнить команду и разобраться, что она делает и что сохраняется в `file.log`<br /><br />    `env -i bash -x -l -c 'echo hello_there!' > file.log 2>&1`<br /><br />_\*\* и \*\*\* не обязательны к выполнению. Задачи на интерес_

**Comment by Rvlt135** [comment]
@AlexPykavy Выполнил задание без дополнительных пунктов с звездочками в ветке homework-3

**Comment by AlexPykavy** [comment]
Отлично, принмается!
